In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import KBinsDiscretizer
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn import svm
from sklearn.metrics import accuracy_score
import pickle

In [2]:
data = pd.read_excel("datakuisoner.xlsx")
df = pd.DataFrame(data.loc[:,['Outcome','JumlahKepanitiaan','JumlahJamTidur','LamaPerjalanan','Olahraga','Curhat']])
df["Outcome"].replace({"Iya": 1, "Tidak": 0}, inplace=True)
print(df)

     Outcome  JumlahKepanitiaan  JumlahJamTidur  LamaPerjalanan  Olahraga  \
0          1                  7               3              25         0   
1          1                  9               3              40        10   
2          0                  7               4              30        10   
3          1                  7               5              40         5   
4          1                  4               3              30        13   
..       ...                ...             ...             ...       ...   
124        0                  2               8              15       100   
125        0                  1               9              10        70   
126        0                  0               9              45        90   
127        0                  2              10              45         0   
128        0                  3               7              10       100   

     Curhat  
0         6  
1         6  
2         3  
3         6  
4    

In [3]:
x = df.drop(columns="Outcome", axis=1)
y = df['Outcome']
print(x)
print(y)

     JumlahKepanitiaan  JumlahJamTidur  LamaPerjalanan  Olahraga  Curhat
0                    7               3              25         0       6
1                    9               3              40        10       6
2                    7               4              30        10       3
3                    7               5              40         5       6
4                    4               3              30        13       5
..                 ...             ...             ...       ...     ...
124                  2               8              15       100       0
125                  1               9              10        70       0
126                  0               9              45        90       0
127                  2              10              45         0       2
128                  3               7              10       100       0

[129 rows x 5 columns]
0      1
1      1
2      0
3      1
4      1
      ..
124    0
125    0
126    0
127    0
128    0
N

In [4]:
scaler = MinMaxScaler()
scaler.fit(x)
x = scaler.transform(x)
print(x)

[[0.58333333 0.         0.23529412 0.         0.66666667]
 [0.75       0.         0.41176471 0.08333333 0.66666667]
 [0.58333333 0.14285714 0.29411765 0.08333333 0.33333333]
 [0.58333333 0.28571429 0.41176471 0.04166667 0.66666667]
 [0.33333333 0.         0.29411765 0.10833333 0.55555556]
 [0.16666667 0.71428571 0.05882353 0.25       0.11111111]
 [0.41666667 0.14285714 0.47058824 0.08333333 0.55555556]
 [0.16666667 0.71428571 0.02352941 0.45833333 0.        ]
 [0.08333333 0.85714286 0.11764706 0.75       0.        ]
 [0.58333333 0.         0.64705882 0.         0.44444444]
 [0.41666667 0.14285714 0.29411765 0.         0.66666667]
 [0.08333333 0.57142857 0.05882353 0.75       0.        ]
 [0.5        0.14285714 0.29411765 0.08333333 0.55555556]
 [0.5        0.14285714 1.         0.08333333 0.44444444]
 [0.75       0.         0.76470588 0.         0.55555556]
 [0.83333333 0.14285714 0.82352941 0.08333333 0.66666667]
 [0.83333333 0.14285714 0.29411765 0.08333333 0.77777778]
 [0.16666667 0

In [5]:
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.3, random_state=42)

In [6]:
kbins = KBinsDiscretizer(n_bins=4, encode='ordinal', strategy='uniform', random_state=42)
x_train = kbins.fit_transform(x_train)
x_test = kbins.fit_transform(x_test)

c:\Users\reyha\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\preprocessing\_discretization.py:248: FutureWarning: In version 1.5 onwards, subsample=200_000 will be used by default. Set subsample explicitly to silence this warning in the mean time. Set subsample=None to disable subsampling explicitly.
  warnings.warn(
c:\Users\reyha\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\preprocessing\_discretization.py:248: FutureWarning: In version 1.5 onwards, subsample=200_000 will be used by default. Set subsample explicitly to silence this warning in the mean time. Set subsample=None to disable subsampling explicitly.
  warnings.warn(


In [7]:
classifier = svm.SVC(random_state=0, kernel='linear')
classifier.fit(x_train, y_train)
y_prediction = classifier.predict(x_test)
accuracy_SVM = round(accuracy_score(y_test, y_prediction)* 100, 2)


In [8]:
input_data = (7,3,25,0,6)
input_data_array = np.array(input_data)
input_data_reshape = input_data_array.reshape(1,-1)
std_data = scaler.transform(input_data_reshape)
prediction = classifier.predict(std_data)
if (prediction[0] == 0):
    print("Anda tidak stress")
else:
    print("Anda stress")

Anda stress


c:\Users\reyha\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  warnings.warn(


In [9]:
filename = "data_stress.sav"
pickle.dump(classifier, open(filename,'wb'))